FROM node:16
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
CMD ["node", "server.js"]



#docker build . -t mahendra1904/node-app    //// build docker image
#docker run -p 5000:5000 -d mahendra/node-app  ///// run docker image and make container
